"""create initial RFID tables

Revision ID: b13f20d3555f
Revises: 
Create Date: 2026-09-07 16:18:44.606781
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b13f20d3555f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reader_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_index(op.f('ix_readers_reader_code'), 'readers', ['reader_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_uid'), 'badges', ['uid'], unique=True)
    op.create_index(op.f('ix_badges_user_id'), 'badges', ['user_id'], unique=False)
    op.create_table('access_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_events_badge_id'), 'access_events', ['badge_id'], unique=False)
    op.create_index(op.f('ix_access_events_occurred_at'), 'access_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_access_events_reader_id'), 'access_events', ['reader_id'], unique=False)
    op.create_index(op.f('ix_access_events_uid'), 'access_events', ['uid'], unique=False)
    op.create_index(op.f('ix_access_events_user_id'), 'access_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_events_user_id'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_uid'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_reader_id'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_occurred_at'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_badge_id'), table_name='access_events')
    op.drop_table('access_events')
    op.drop_index(op.f('ix_badges_user_id'), table_name='badges')
    op.drop_index(op.f('ix_badges_uid'), table_name='badges')
    op.drop_table('badges')
    op.drop_table('users')
    op.drop_index(op.f('ix_readers_reader_code'), table_name='readers')
    op.drop_table('readers')
    # ### end Alembic commands ###

